version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Kukulkano/dv-vault"

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "php"
enabled = true