= DataVaccinator Vault
:author: DataVaccinator Team
:email: info@datavaccinator.com

This is the DataVaccinator Vault platform. It has to be installed on some Linux environment in order to provide a REST API for pseudonymisation services.

== The DataVaccinator Vault platform offers

* **Multi tenant use** (multiple service providers served on the same platform).
* **Word based search** using an encrypted index which ensures no readable information on server side.
* Can use link:https://letsencrypt.org/[**Let's Encrypt** certificates] out of the box.
* Supports both *IPv4* and *IPv6* and allows listening on multiple addresses (for the same domain).
* Fully automatic **IP whitelisting** by only serving API requests from dedicated IP addresses.
* DataVaccinator Vault supports working behind **proxy servers** and **loadbalancers** (like link:http://www.haproxy.org/[HAProxy]).
* It supports link:https://fetch.spec.whatwg.org/#cors-protocol[**CORS**] to avoid issues with cross origin requests.
* **Installer-Script** supports **CentOS**, **Red Hat**, **Rocky Linux**, **Arch Linux**, **Suse Linux**, **Ubuntu** and **Debian** systems (all x86_64).
* Installer-Script automatically generates **systemd daemon**, system user and group, database user and database structure.

== What is it good for?
The DataVaccinator Vault protects your sensitive data and information against abuse. At the very moment when data is being generated, the service splits that data and uses advanced pseudonymisation techniques to separate content from identity information. Thus, the DataVaccinator Vault reduces cyber security risks in the health, industry, finance and any other sector and helps service providers, device manufacturers, data generating and data handling parties to manage sensitive data in a secure and GDPR-compliant manner. In contrast to other offerings, DataVaccinator industrialises pseudonymisation, thereby making pseudonymisation replicable and affordable. 

Get more information, support and contact at <https://www.datavaccinator.com>.

== It requires (for execution):

* Some **Linux** server (Intel/AMD, x86_64)
* link:https://www.cockroachlabs.com/product[**CockroachDB**] database and drivers

== It requires (for development):

* Some **Linux** server (Intel/AMD, x86_64)
* link:https://www.cockroachlabs.com/product[**CockroachDB**] database and drivers
* **go** compiler (1.16 or higher)
* **php 7** (for migration tool and test scripts)
* Preferable some IDE (like link:https://code.visualstudio.com/[VSCode], link:https://atom.io/[Atom], link:https://github.com/fatih/vim-go[VIM-GO] or link:http://liteide.org/[LiteIDE])

== What is missing:

* There is currently no gui or any comandline options for managing service providers (add/edit/delete).
* Currently no support for ARM systems.
* No support for Windows systems.

== Get started
In order to run a DataVaccinator Vault, please follow this guide for installation on a dedicated Linux machine:

1. Install link:https://www.cockroachlabs.com/product[CockroachDB] on the machine.
2. Download the latest DataVaccinator setup (...setup.sh) from link:https://github.com/Kukulkano/dv-vault/releases/tag/release[GitHub releases page] to some temporary directory on your machine.
3. Run it like this: +
   `sudo sh dv-vault-1.0.0_x86_64_setup.sh`
4. Follow the steps from the setup script.
5. Edit the `conf.json` file to your needs. 
   - By default it is located at `/opt/vaccinator/config.json` folder.
   - Check the link:./docs/vaccinator-config.adoc[docs/vaccinator-config.adoc] for details about the configuration options.
   - Remember to use `sudo` to edit this file.
6. Start the service using +
   `sudo systemctl start vaccinator`
7. Control service start using +
   `journalctl -et vaccinator`
8. Create/edit a service provider login
   - Run CockroachDB console using +
   `cockroach sql --insecure`
   - Run +
   `use vaccinator;` +
   to make the vaccinator database the default.
   - Run +
   `select * from provider;` +
   to get a list of the providers.
9. Update the default entry with a password and allowed IPs like this (example): +
   `UPDATE provider SET name='myName', password='myPassword', ip='192.168.1.10 127.0.0.1' WHERE providerid=1;`

== License information
DataVaccinator Vault is released as free software under the Affero GPL license (AGPL). You can redistribute it and/or modify it under the terms of this license which you can read by viewing the included LICENSE file or online at www.gnu.org/licenses/agpl.html
