= Cockroach setup
:author: DataVaccinator Team
:email: info@datavaccinator.com
:toc:
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

include::glossary_include.adoc[]

The following examples and calls are for CentOS (7, 8). You may need to adapt package names and pathes to run on other systems.

== Download and setup

If you're running Debain systems (eg Ubuntu) you may need to rename _yum_ with _apt_.

The below script installs _tar_, _vim_, _zip_ and _bind-utils_ (dig) for later use. Upon this, it downloads the given cockroach install file and extracts the content to current folder. Then, it copies the binaries to `/usr/local/bin` folder. Now it sets the timezone (useful for later node sync). Now it creates a user _cockroach_. It is later used by systemd to run the database. Now, the binaries are getting owned by the cockroach user and finally, the temp folder is deleted.

IMPORTANT: You need to adapt the cockroach download URL (2nd line) and the folder name (3rd and last line).

NOTE: Get the most recent setup path from https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html.

[source,shell]
----
yum install tar vim zip bind-utils
curl https://binaries.cockroachdb.com/cockroach-v21.1.3.linux-amd64.tgz | tar -xz
cp -i cockroach-v21.1.3.linux-amd64/cockroach /usr/local/bin/
timedatectl set-timezone Europe/Berlin
useradd cockroach
chown cockroach /usr/local/bin/cockroach
rm -rf cockroach-v21.1.3.linux-amd64/
----

== Setup daemon (systemd)

=== Setup cockroach as daemon

Create the following file: `/etc/systemd/system/cockroach.service`

Put in the following content:

[source]
----
[Unit]
Description=Cockroach Database cluster node
Requires=network.target

[Service]
Type=simple
WorkingDirectory=/home/cockroach
ExecStart=/usr/local/bin/cockroach start-single-node --listen-addr=127.0.0.1 --insecure
ExecStop=/usr/local/bin/cockroach quit --insecure --host=127.0.0.1
Restart=always
RestartSec=10
RestartPreventExitStatus=0
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=cockroach
User=cockroach

[Install]
WantedBy=default.target
----

IMPORTANT: The above example is for a *single node* and *local database*. +
*This is not for production!* +
If you're setting up a production cluster, the start-mode, IPs and cockroach comandline options will be different!

=== Initialize the daemon

Now, in order to start the service, execute the following:

[source,shell]
----
systemctl enable cockroach.service
systemctl daemon-reexec
systemctl start cockroach.service
----

Now check using `journalctl -et cockroach` if the service is up and running or if there are issues.

== Initialize the database

Run this to initialize your database:

[source,shell]
----
cockroach init --insecure --host=127.0.0.1
----

== Check if database is available

Run the following command to see if the database is running:

[source,shell]
----
cockroach sql -e "SELECT * FROM system.users;" --insecure --host=127.0.0.1
----

This will show you a list of database users. If it triggers errors, you very likely have an issue.