= DataVaccinator Vault Protocol
:author: DataVaccinator Team
:email: info@datavaccinator.com
:toc:
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Client Protocol

This chapter is describing the protocol for using the DataVaccinator Vault pseudonymisation service. This is the internal communication for the DataVaccinator Vault service and not to become implemented by customers developers.

The client protocol is currently implemented in JavaScipt and offers access to all pseudonymisation functions and management functions of DataVaccinator Vault. *It is not the endpoint presented to the developers.* Instead, this is communication between the JavaScript class and the DataVaccinator Vault itself.

The endpoint interface for developers is described in the documentation for the respective endpoint implementation (eg JavaScript class).

== Implementation details

The protocol is REST based and works by sending information using POST requests. 

The functionality at the service provider is established by some sort of intermediate handling between client and identity management (proxy).
The described client protocol is used between the client implementation and the DataVaccinator Vault. The service provider always forwards all the requests to the DataVaccinator Vault and only adds his access information fields to the request (*sid* and *spwd*). The results are also forwarded back to the calling client then.

A few functions like <<add_new_dataset, add>> also return data that is interesting for the service provider. He can use this to update his own database.

The JSON encoded structure, containing the function name and all needed parameters, is typically sent in a POST field named _json_.
A typical call consists of some operation code (_op_) and some field containing the encrypted data for the DataVaccinator Vault (_data_).
The optional _uid_ field is for API users to identify calls to some specific user or assigning return values to internal identifiers. It can be unset (empty) or contain some value. It is not used for DataVaccinator identity management.

All calls will return a JSON encoded string, containing the result of the operation and additional information.

There is always a _status_ field returned. If it is not _OK_, something went wrong. In this case, the status is either _INVALID_ or _ERROR_.
An additional _code_ field contains the error number and the _desc_ field contains additional information about the error (only if _status_ is not _OK_).

=== Payload

The _data_ field contains encrypted payload for the identity management. It is usually named Vaccination Data. It is encrypted due to contained receipt.
A data field is always encoded like this:

 receipt:cs:iv:payload

* The _receipt_ defines the algorithm used for encryption.
* The _cs_ value is the checksum of the used app-id key (last byte in hex, see app-id description).
* The _iv_ is the start vector/nonce for encryption in hex encoding.
* The _payload_ is the hex or base64 encoded JSON string with encrypted Vaccination Data.

It typically looks like in this example:

 aes-256-cbc:f7:29a1c8b68d8a:Z2Zkc2dmZG1rZyBmZ(...)XI0N2Z2IDZyNHkzMmY0Mw==

This encryption is done automatically by the client API and happens transparently for the end users and service provider developers.

NOTE: By this encryption, using the app-id as key, the service provider and the DataVaccinator Vault both do not have access to the content (for example patient data). The checksum as part of the receipt allows later verification, if the dataset was encrypted with one or maybe a newer app-id.
This is useful, for example, if the *changeAppId()* class failed during processing (please refer to *changeAppId()* function description in JavaScript class documentation).

NOTE: The above chosen AES cipher is just the reference implementation. You can also use others (like Twofish). The only thing to respect is the encoding using hex for the _cs_ and the _iv/nonce_.

=== Authentication
Currently, the DataVaccinator Vault supports a simple authentication schema. For this, every call needs to provide both ID and password (*sid* and *spwd*). In combination with IP whitelisting, this is already a good level of security.

*Some additional thoughts about authentication*

Nevertheless, if IP whitelisting is not practicable, we still consider it as hard to break in. The reason is the fact that even if you manage to log-in as a service provider, you still only can receive any data if you know the VIDs of the data. As long as you don't know, it is hard to get some data. And even if you get that, you still receive encrypted data. This is encrypted by the password the client software used for encryption and typically not known by the service provider.

A future version may add some sort of hash challenge and a time limited session token to prevent replay attacks and add some additional barrier. Also, if the *sid* would be hard to guess, we might block such service provider after trying to log in with a wrong password. This is still to implement.

We currently decided against *OAuth 2.0* or *OpenID Connect* for API authentication. Mainly because it adds a third party dependency that would shut down the whole API if the identity provider is not available (outage, connectivity etc). It also would add more complexity and consumes more bandwith. Territorial and legal questions regarding a reliable identity provider have also come up. For example, to avoid big US players like Google, Microsoft or Amazon, you first would have to find another identity provider that fullfils your needs. *JWT* seem unadequate for our needs, too.

== Transport encryption

Of course, all API REST calls are using standard SSL connections (https).

The _data_ field is encrypted using the SHA256 from the end users app-id as password. We start implementing AES encryption with CBC mode and individual IV. See above chapter about implementation details.

== Error codes

In case of an error, the _status_ value is not OK, instead it is either INVALID or ERROR. INVALID means that some data you provided triggered the error and ERROR is some DataVaccinator related internal error. If INVALID, you need to check your input.

The system then returns two additional fields:
[cols="1,4,2"]
|=======
|code	|desc	|status

|1	|Missing Parameters.	|INVALID
|2	|Wrong Protocol.	|INVALID
|3	|Your software seems outdated.	|INVALID
|4	|The account was locked due to possible misuse.	|INVALID
|5	|Invalid credentials (check sid and spwd).	|INVALID
|6	|Invalid encoding (check data values and JSON integrity).	|INVALID
|7	|Not found (vid is not found in the system).	|INVALID
|8	|Invalid partner (you are not allowed to access foreign data).	|INVALID
|9	|Invalid parameter (some parameter exceeds limits or ranges).	|INVALID
|10 |Not allowed for published data. | INVALID
|99	|Some internal service error happened. Please contact support.	|ERROR
|=======

== Example protocol commmunication

This is an example request:
[source,json]
----
{
    "version": 2,
    "op": "get",
    "sid": 1,
    "spwd": "myPassword",
    "vid": "72f641db6bf18847a33a615501f3a571",
    "uid": 12345
}
----

And the resulting example answer:
[source,json]
----
{
    "status": "OK",
    "uid": "12345",
    "data": {
        "72f641db6bf18847a33a615501f3a571": {
            "data": "aes-256-cbc:f7:29a1c8b68d8a:Z2Zkc2dmZG1rZyBmZ (...)
                     XI0N2Z2IDZyNHkzMmY0Mw==",
            "status": "OK"
        }
    }
}
----


== PING function

You may want to verify if DataVaccinator Vault is alive and working by simply calling it's *ping* function like this:

https://domain/ping or http://domain:8080/ping

If it does not return with "OK", something is wrong (eg database backend not available or service not running at all).

TIP: This *ping* service does not consume many ressources, so you can call this every minute to verify the status of your DataVaccinator Vault instances. We suggest to use a networking timeout of maximum two seconds for this.

== API functions

This chapter describes all available *op* functions of the protocol, their meaning, parameters and expected results.

=== Add new dataset

This call is adding a new dataset to the system (eg PID).
[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|add
|data	|Encrypted payload containing all the Vaccination Data to be stored (string blob, use base64 encoding for binary data). Please follow the encoding scheme described in <<implementation_details, Implementation Details>>.
|uid	|User identifier provided by the API user.
|words	|Array of SearchHashes to add for <<search, search function>> (optional).
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|vid	|New Vaccination ID for the newly generated payload (also VID). This may be stored by the service provider and get assigned to the calling client (identified by uid).
|=======

IMPORTANT: As the service provider, if you forward some positive result of this function to the client, please take the returned _vid_ and add this to your service provider database while assigning to the user. By this, you are able to send your client software a complete and up to date list of all VIDs at any time.

=== Update dataset

This call is updating an existing entry.

[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|update
|data	|Encrypted payload containing all the Vaccination Data to get updated (string blob, use b64 encoding for binary data).
|vid	|Vaccination ID to update.
|uid	|User identifier provided by the API user.
|words	|Array of SearchHashes to add for search function (optional).
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|=======

IMPORTANT: Updating payload data is critical to the local caches of the JS class. If multiple systems accessing the data, the cache of the other systems is outdated after some update. Only the system which did the changes is up to date. +
 +
Therefore, this has to be handled special: Please create a unique code (eg time stamp or random number) in case you forward some <<update_dataset, update>> request to the DataVaccinator Vault. This code has to be sent to your client application as soon as possible (maybe as part of your protocol).
There, please call the *wipeCache()* function with this code every time.
This will trigger the local cache to refresh in case something has changed.
Please refer to the *wipeCache()* function description in JavaScript class documentation.

=== Retrieve dataset

This call is retrieving the data of one or more existing entries.
[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|get
|vid	|Vaccination ID to retrieve data from.

Multiple VIDs can get submitted as array of VIDs or as a string with concatenated VIDs using blank as divider character. The allowed maximum of VIDs is 500 per request.

|uid	|User identifier provided by the API user.
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|data	|This contains the Vaccination Data payload(s). Payload always comes as a object array where the VID is the key. It has one entry in case only one VID was requested and multiple entries in case of multiple results. Every given VID creates a return value, even if it was not found or suspicious. Note: The order is not guaranteed to be the same as provided in the request!
|=======

The returned result always confirms to this JSON schema, written as a complete example answer:

[source,json]
----
 {
   "status": "OK",
   "version": "0.0.0.0",
   "uid": 12345,
   "data": {
     "f315db7b01721026308a5346ce3cb513": {
       "status": "OK",
       "data": "aes-256-cbc:7f:29a1c8b68d8a:btewwyzox3i3fe4cg6a1qzi8pqoqa55orzf4bcxtjfcf5chep998sj6"
     },
     "2ff18992cfc290d3d648aea5bdea38b1": {
       "status": "NOTFOUND",
       "data": false
     }
   }
 }
----

The above example showing the result of a request with two VIDs.
The first was a valid request, the second was some unknown entry.

=== Retrieve published dataset

This call is retrieving the data of one or more existing entries which have been uploaded using the <<publish, publish>> function.
[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|getpublished
|vid	a|Vaccination ID to retrieve data from.

Multiple VIDs can get submitted as array of VIDs or as a string with concatenated VIDs using blank as divider character. The allowed maximum of VIDs is 500 per request.

[CAUTION]
Due to the nature of the publishing feature, this will only return data which was uploaded using the <<publish, publish>> function. +
Also, it will return data even if the requesting service provider is not the one who uploaded (sid).

|uid	|User identifier provided by the API user.
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|data	|This contains the Vaccination Data payload(s). Payload always comes as a object array where the VID is the key. It has one entry in case only one VID was requested and multiple entries in case of multiple results. Every given VID creates a return value, even if it was not found or suspicious. Note: The order is not guaranteed to be the same as provided in the request!
|=======

The returned result is identical to the one described for the <<retrieve_dataset, get>> function. Please look there for reference.

=== Delete dataset

This call is deleting an existing entry.
[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|delete
|vid	|Vaccination ID to delete from DataVaccinator Vault.

Multiple VIDs can get submitted as array of VIDs or as a string with concatenated VIDs using blank as divider character. The allowed maximum of VIDs is 500 per request.

|uid	|User identifier provided by the API user.
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|=======

CAUTION: There is no way to restore a deleted entry!

=== Check connection

This is just a simple "ping" sort of call to verify if the service is available. It does nothing.
It is just answering with status "OK" and giving generic information about the platform. This is also not verifying the validity of the request using `sid` and `spwd`.
[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|check
|uid	|User identifier provided by the API user.
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|OK
|uid	|User identifier provided by the API user during call (only if it was provided).
|version	|Server version.
|time	|Current date and time on the server (YYYY-MM-DD HH:MM:SS).
|plugins	|An array of objects mentioning available plugins. Each object contains at least a _name_, _vendor_ and _license_ field.
|=======

=== Search

The search function is only available if the DataVaccinator Vault is running the *search* plugin.
You can verify this using the "check" function.
[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|search
|words	|One or more SearchHashes to search for. Multiple SearchHashes can get submitted as array of SearchHashes or as a string with concatenated SearchHashes using blank as divider character.
|uid	|User identifier provided by the API user.
|=======

Result:
[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|vids	|Array of VIDs (Vaccination IDs) that matched your search. Empty array if there are no matches.
|=======

=== Publish

This call is very similar to the <<add_new_dataset, add>> function. But while normal datasets can get only accessed by the originating service provider, published data can get accessed/retrieved by other service providers, too. For this, they only need to know the VID.

NOTE: For security reasons, they also need valid access credentials (sid, spwd, allowed ip).

While the data in DataVaccinator has to be always encrypted, the people who retrieve this data will need the correct password to decrypt. Please refer to the JavaScript class documentation for further details on this.

The major differences to the <<add_new_dataset, add>> function are:

. Payload data can not get updated (only deleted by the originator).
. Publish does not support word search (no words accepted).
. It needs a time period after that it is automatically deleted.


[cols="1,4"]
|=======
|Field	|Description

|version	|2 (current protocol version)
|op	|publish
|data	|Encrypted payload containing all the Vaccination Data to be stored (string blob, use base64 encoding for binary data). Please follow the encoding scheme described in <<implementation_details, Implementation Details>>.
|uid	|User identifier provided by the API user.
|period	|The number of days after which this data is automatically deleted. Valid ranges are 1 to 365. Other values will trigger an error.
|=======

[cols="1,4"]
|=======
|Field	|Description

|status	|Either OK, INVALID or ERROR. See generic description for details.
|uid	|User identifier provided by the API user during call (only if it was provided).
|vid	|New Vaccination ID for the newly generated dataset (also VID). This may be stored by the service provider and get assigned to the calling client (identified by uid).
|=======

= Implementation of protocol forward

This chapter explains, what a service provider has to do to successfully handle and forward REST protocol requests.

== Forward requests by adding service provider credentials

In general, all requests have to become forwarded to the DataVaccinator Vault URL. If the requests are forwarded (eg from vaccinatorJSClass), the authentication has to become added. After processing you get the answer. You have to send back this answer to the calling end user client (eg web browser API).

For authentication at the DataVaccinator Vault, these two values must be provided during your forward:

[cols="1,4"]
|=======
|Field	|Description

|sid	|The service provider ID. This is provided to the service provider by the vaccinator service staff.
|spwd	|The service provider password. This is provided to the service provider by the vaccinator service staff.
|=======

There are two options available for submitting the authentication:

. The POST contains two additional form values _sid_ and _spw_.
. The JSON encoded in _json_ data value is supplemented by two additional values _sid_ and _spw_.

=== Option 1 with additional POST values (recommended)
The POST already contains a _json_ key with the JSON encoded API call. You can add _sid_ and _spwd_ values to the form POST to add DataVaccinator Vault authentication.

=== Option 2 with supplemented json
The JSON encoded in _json_ data value must get supplemented by the two additional values.

The drawback of this method is the need to decode, add the values and re-encode the json request. This is not needed for option 1.

== Observe and enrich function calls

In addition, the service provider has to observe the functions to provide additional functionality required.

=== update call

The <<update_dataset, update>> call will out date all other participants local caches. Therefore, they need to know about this. The only party able to tell them is you.

This is done by acting in case of a positive <<update_dataset, update>> call. In case the DataVaccinator Vault announces success, please generate a time stamp (or random token) and provide it to all affected clients. By knowing the VID from the request, you should be able to know the affected logins.
You send them this time stamp with their next request and they will have to call the *wipeCache()* class function with this as parameter. 

If the API recognises this time stamp/token as already known, nothing will happen. If it does not know this value yet, it will wipe it's cache and regenerate it on demand later.

=== ALL user requests (get, update and delete)

Here you might want to verify it the logged in user is allowed to handle data about this VID. This would be some important security layer to prevent manipulations in local client to retrieve or manipulate data of VIDs the user is not allowed to.

Here, please forward the request only if the user is allowed to. Please follow the protocol description above and, if not allowed, send some status _INVALID_ and code 7 (vid not found).

Please see examples/ folder in this repository to find a PHP example about forwarding DataVaccinator calls (eg from JavaScript class).
