= vaccinator configuration options
:author: DataVaccinator Team
:email: info@datavaccinator.com

== config.json

The *config.json* has be located at the same place the vaccinator executable is located (default is /opt/vaccinator/). 

The default content of config.json looks like this:
[source,json]
----
{ 
    "connectionString": "connectionString", 
    "maxConnections": 0,
    "listenIP": "",
    "listenPort": 443,
    "useLetsEncrypt": 0,
    "debugMode": 0,
    "IPExtractor": "",
    "disableIPCheck": 0,
    "CORSDomains": ""
}
----

This are the available options and their meanings:

[cols="1,3"]
|=====
|Parameter | Description

|connectionString
|This is the database connection string for the CockroachDB.

Reference: https://www.postgresql.org/docs/11/libpq-connect.html#LIBPQ-CONNSTRING

|maxConnections
|This value determines how many database connections the DataVaccinator keeps in his connection pool. If you specify *0* (which means *auto*), it will multiply the number of CPU cores (incl. hyperthreading) with 3.

Reference: https://www.cockroachlabs.com/docs/v21.1/connection-pooling.html#sizing-connection-pools

|listenIP
|The IPv4 address to listen to. If you keep it empty, it listens on all available interfaces. Default is empty string.

|listenPort
|Set the port to listen to. This value must be set. For SSL connections (https), set to 443.

|useLetsEncrypt
|Set to *1* if you like to let DataVaccinator use Let's Encrypt certificate automatically. Default is *0*.

|debugMode
|Set to *1* if you like to get additional debug information to StdOut. Default is *0*.

|IPExtractor
a|If not set (empty string), the DataVaccinator will determine source IP addresses by using the network layer.

In some cases, behind loadbalancers or proxy servers, this will return the same IP for all requests. Here you can advise to use other headers. The following values are available:

. *XFF* -> Using the _X-Forwarded-For_ header
. *REALIP* -> Using the _X-Real-IP_ header

|disableIPCheck
a|If set to *1*, the DataVaccinator will not verify the IP address of the calling client against the "IP" field in database table "provider". Default is *0*.

CAUTION: This is useful in development and testing environments, but should not be used in production.

|CORSDomains
a|Enables CORS to allow cross domain access (avoid issues with cross-origin-policy). Refer https://fetch.spec.whatwg.org/#cors-protocol[CORS Protocol definition] for further details.

You can provide an empty string ("") to disable this feature (default).

To allow all domains, enter "***". 

If you like to define specific urls, you can enter complete urls. Divide multiple allowed urls using comma.

Example: "http://127.0.0.1,https://someDomain.de"
|=====