name: Build Setup File

# Controls when the action will run. 
on:
  push:
    branches:
      - master

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Makeself
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -yq install makeself
        
      - name: Compile DataVaccinator Setup
        run: make VERSION=1.0.$GITHUB_RUN_ID
        
      # Removes the latest release, so that we can create a new one in its place
      - name: Delete latest release
        uses: ame-yu/action-delete-latest-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (optional) Removes the tag associated with the latest release
      - name: Delete release tag
        run: |
          git tag -d release
          git push origin :release
        continue-on-error: true # in case there's no existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Release notes"
          name: Latest
          tag_name: release
          files: ./setup/dv-vault-*_setup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Check-in DataVaccinator Vault Setup
        #run: |
        #  git config --global user.email "build@datavaccinator.com"
        #  git config --global user.name "GitHub Automatic Build"
        #  git add ./setup/dv-vault-*_setup.sh
        #  git commit -m"Re-compiled most recent setup"
        #  git push
