name: Build Setup File

# Controls when the action will run. 
on:

  # Currently only manual triggers
  workflow_dispatch:

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Makeself
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -yq install makeself
        
      - name: Compile DataVaccinator Setup
        run: make VERSION=1.0.0

      - name: Check-in DataVaccinator Vault Setup
        run: |
          git config --global user.email "build@datavaccinator.com"
          git config --global user.name "GitHub Automatic Build"
          git add ./setup/dv-vault-*_setup.sh
          git commit -m"Re-compiled most recent setup"
          git push
