CREATE DATABASE vaccinator;
USE vaccinator;
CREATE SCHEMA dv;

CREATE USER IF NOT EXISTS <USER>;
GRANT ALL ON DATABASE vaccinator TO <USER>;
GRANT USAGE ON SCHEMA dv TO <USER>;

CREATE TABLE dv.data (
  VID BYTES NOT NULL,
  PAYLOAD BYTES NOT NULL,
  PROVIDERID SMALLINT NOT NULL,
  CREATIONDATE TIMESTAMPTZ NOT NULL,
  DURATION SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (VID)
);

CREATE TABLE dv.provider (
  PROVIDERID SMALLINT NOT NULL,
  NAME STRING NOT NULL,
  DESCRIPTION STRING NOT NULL DEFAULT '',
  PASSWORD STRING NOT NULL,
  IP STRING NOT NULL DEFAULT '',
  CREATIONDATE TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (PROVIDERID)
);

CREATE TABLE dv.search (
  VID BYTES NOT NULL,
  WORD STRING NOT NULL,
  INDEX (WORD),
  INDEX (VID)
);

CREATE TABLE dv.audit (
  ID SERIAL,
  LOGTYPE INT NOT NULL,
  LOGDATE TIMESTAMPTZ NOT NULL,
  PROVIDERID SMALLINT NOT NULL,
  LOGCOMMENT STRING DEFAULT '',
  PRIMARY KEY (ID)
);

INSERT INTO dv.provider (providerid, name, password, ip, creationdate) 
  VALUES(1, 'test', 'vaccinator', '127.0.0.1', now());